name: deploy

on:
  push:
    branches: ["main", "develop"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup pages
        uses: actions/configure-pages@v3
      - name: Deploy static
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./target
          distination: |
            if [ ${{ github.action_ref_name }} == "main" ]; then
              ./prod
            else
              ./dev
            fi
