name: deploy

on:
  push:
    branches: ["main", "develop"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./target
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          destination_dir: |
            if [[ ${{ github.action_ref_name }} == "main" ]]; then
              ./prod
            else
              ./dev
            fi
      # - name: Deploy static
      #   uses: actions/jekyll-build-pages@v1
      #   with:
      #     source: ./target
      #     destination: |
      #       if [ ${{ github.action_ref_name }} == "main" ]; then
      #         ./prod
      #       else
      #         ./dev
      #       fi
