name: node-test
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: change directory
        run: cd nodeModule
      - name: install
        run: npm ci
      - name: run test
        run: npm run test
