name: Code quality

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./nodeModule

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.2.2
      - name: Run Biome
        run: biome ci .
